spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contact_list
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database:
    database-platform: org.hibernate.dialect.PostgreSQLDialect